<?php

return [
    'defaults' => [
        'timeout_seconds' => 2,
        'retry_attempts' => 2,
        'rollback' => 'legacy_runtime_fallback',
    ],

    'adapters' => [
        'payment_gateway' => [
            'context' => 'PaymentGateway',
            'feature_ids' => ['SF-015', 'API-004'],
            'endpoint' => env('INTEGRATION_PAYMENT_GATEWAY_URL', 'https://payment.example.test/authorize'),
            'method' => 'POST',
            'config_path' => 'payment/paypal/sandbox',
            'secret_key' => 'services.payment_gateway.token',
            'sandbox' => true,
            'providers' => ['PayPal', 'Authorize.Net', 'Paygate', 'Phoenix_Moneybookers'],
            'webhook' => 'IPN callback signature with return URL and cancel URL',
        ],
        'shipping_carrier' => [
            'context' => 'ShippingCarrier',
            'feature_ids' => ['API-005', 'CJ-002'],
            'endpoint' => env('INTEGRATION_SHIPPING_CARRIER_URL', 'https://shipping.example.test/rates'),
            'method' => 'POST',
            'config_path' => 'carriers/ups/sandbox',
            'secret_key' => 'services.shipping_carrier.api_key',
            'sandbox' => true,
            'providers' => ['UPS', 'USPS', 'FedEx', 'DHL'],
        ],
        'currency_rate' => [
            'context' => 'CurrencyRate',
            'feature_ids' => ['API-006', 'AD-018', 'CJ-004'],
            'endpoint' => env('INTEGRATION_CURRENCY_RATE_URL', 'https://currency.example.test/rates'),
            'method' => 'GET',
            'config_path' => 'currency/import/service',
            'secret_key' => 'services.currency_rate.token',
            'sandbox' => true,
        ],
        'google_analytics' => [
            'context' => 'GoogleAnalytics',
            'feature_ids' => ['SF-016', 'API-006'],
            'endpoint' => env('INTEGRATION_GOOGLE_ANALYTICS_URL', 'https://analytics.example.test/collect'),
            'method' => 'POST',
            'config_path' => 'google/analytics/account',
            'secret_key' => 'services.google_analytics.token',
            'sandbox' => true,
        ],
        'google_base' => [
            'context' => 'GoogleBase',
            'feature_ids' => ['SF-016', 'API-006', 'CJ-017'],
            'endpoint' => env('INTEGRATION_GOOGLE_BASE_URL', 'https://google-base.example.test/items'),
            'method' => 'POST',
            'config_path' => 'google/base/account',
            'secret_key' => 'services.google_base.token',
            'sandbox' => true,
        ],
        'email_provider' => [
            'context' => 'EmailProvider',
            'feature_ids' => ['API-006', 'AD-018'],
            'endpoint' => env('INTEGRATION_EMAIL_PROVIDER_URL', 'https://email.example.test/send'),
            'method' => 'POST',
            'config_path' => 'system/smtp/host',
            'secret_key' => 'mail.mailers.smtp.password',
            'sandbox' => true,
        ],
        'erp' => [
            'context' => 'Erp',
            'feature_ids' => ['API-006', 'AD-018'],
            'endpoint' => env('INTEGRATION_ERP_URL', 'https://erp.example.test/orders'),
            'method' => 'POST',
            'config_path' => 'project/erp/api',
            'secret_key' => 'services.erp.token',
            'sandbox' => true,
        ],
        'pim' => [
            'context' => 'Pim',
            'feature_ids' => ['API-006', 'AD-018'],
            'endpoint' => env('INTEGRATION_PIM_URL', 'https://pim.example.test/products'),
            'method' => 'POST',
            'config_path' => 'project/pim/api',
            'secret_key' => 'services.pim.token',
            'sandbox' => true,
        ],
        'crm' => [
            'context' => 'Crm',
            'feature_ids' => ['API-006', 'AD-018'],
            'endpoint' => env('INTEGRATION_CRM_URL', 'https://crm.example.test/customers'),
            'method' => 'POST',
            'config_path' => 'project/crm/api',
            'secret_key' => 'services.crm.token',
            'sandbox' => true,
        ],
        'feed' => [
            'context' => 'Feed',
            'feature_ids' => ['API-006', 'AD-018'],
            'endpoint' => env('INTEGRATION_FEED_URL', 'https://feed.example.test/export'),
            'method' => 'POST',
            'config_path' => 'project/feed/api',
            'secret_key' => 'services.feed.token',
            'sandbox' => true,
        ],
        'webhook' => [
            'context' => 'Webhook',
            'feature_ids' => ['API-004', 'API-006'],
            'endpoint' => env('INTEGRATION_WEBHOOK_URL', 'https://webhook.example.test/callback'),
            'method' => 'POST',
            'config_path' => 'payment/webhook/signature',
            'secret_key' => 'services.webhook.signature',
            'sandbox' => true,
            'webhook' => 'payment callback, IPN, signature verification',
        ],
        'oauth' => [
            'context' => 'OAuth',
            'feature_ids' => ['AD-018', 'API-006'],
            'endpoint' => env('INTEGRATION_OAUTH_URL', 'https://oauth.example.test/token'),
            'method' => 'POST',
            'config_path' => 'oauth/consumer/key',
            'secret_key' => 'services.oauth.client_secret',
            'sandbox' => true,
            'oauth' => true,
        ],
        'sandbox' => [
            'context' => 'Sandbox',
            'feature_ids' => ['API-004', 'API-005', 'API-006'],
            'endpoint' => env('INTEGRATION_SANDBOX_URL', 'https://sandbox.example.test/health'),
            'method' => 'GET',
            'config_path' => 'dev/integration/sandbox',
            'secret_key' => 'services.sandbox.token',
            'sandbox' => true,
        ],
        'integration_config' => [
            'context' => 'IntegrationConfig',
            'feature_ids' => ['AD-018', 'API-006'],
            'endpoint' => env('INTEGRATION_CONFIG_URL', 'https://config.example.test/status'),
            'method' => 'GET',
            'config_path' => 'admin/system_config/integrations',
            'secret_key' => 'services.integration_config.token',
            'sandbox' => true,
        ],
    ],
];
