<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DomainFactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('domain_facts')
            ->whereIn('feature_key', ['catalog', 'category', 'product', 'product_media', 'search', 'customer', 'customer_address', 'wishlist', 'compare', 'review', 'tag', 'downloadable', 'cms_page', 'cms_block', 'widget', 'sitemap', 'url_rewrite', 'store_scope'])
            ->whereIn('entity_id', [1001, 1002, 1003, 2001, 2002, 3001, 3002, 3003, 3004, 4001, 4002, 4003, 4004, 4005, 4006, 5001, 5002, 6001, 6002, 7001, 7002, 7003, 7004, 8001, 8002, 9101, 9102, 9103, 9201, 9202, 9203, 9301, 9302, 9303, 9401, 9402, 9403, 10001, 10002, 10003, 10004, 10005, 10006, 10101, 10102, 10103, 10104, 10201, 10202, 10203, 10204, 10301, 10302, 10303, 10304, 10401, 10402, 10403, 10404, 10501, 10502])
            ->whereIn('store_id', [9001, 9002])
            ->delete();

        DB::table('domain_facts')->insert([
            [
                'feature_key' => 'catalog',
                'entity_id' => 1001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Simple Shirt',
                    'sku' => 'simple-shirt',
                    'type' => 'simple',
                    'price' => 29.95,
                    'category' => 'Women',
                    'stock' => 24,
                    'url' => '/women/simple-shirt.html',
                    'short_description' => 'Lightweight cotton shirt for everyday catalog browsing.',
                    'swatch' => 'blue',
                    'rating' => 4.5,
                    'visibility' => 'Catalog, Search',
                ]),
            ],
            [
                'feature_key' => 'catalog',
                'entity_id' => 1002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Configurable Hoodie',
                    'sku' => 'configurable-hoodie',
                    'type' => 'configurable',
                    'price' => 59.00,
                    'category' => 'Gear',
                    'stock' => 8,
                    'url' => '/gear/configurable-hoodie.html',
                    'short_description' => 'Size and color configurable hoodie used for filter and sort checks.',
                    'swatch' => 'black',
                    'rating' => 4.8,
                    'visibility' => 'Catalog, Search',
                ]),
            ],
            [
                'feature_key' => 'catalog',
                'entity_id' => 1003,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'name' => 'Einfaches Hemd',
                    'sku' => 'simple-shirt',
                    'type' => 'simple',
                    'price' => 31.95,
                    'category' => 'Damen',
                    'stock' => 18,
                    'url' => '/de/damen/einfaches-hemd.html',
                    'short_description' => 'Lokalisierte Store-View-Zeile fuer Katalogpruefungen.',
                    'swatch' => 'blau',
                    'rating' => 4.5,
                    'visibility' => 'Katalog, Suche',
                ]),
            ],
            [
                'feature_key' => 'category',
                'entity_id' => 2001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Women',
                    'url_key' => 'women',
                    'is_active' => true,
                    'product_ids' => [3001],
                ]),
            ],
            [
                'feature_key' => 'category',
                'entity_id' => 2002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Gear',
                    'url_key' => 'gear',
                    'is_active' => true,
                    'product_ids' => [3002],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'name' => 'Simple Shirt',
                    'type' => 'simple',
                    'attribute_set' => 'Default',
                    'url_key' => 'simple-shirt',
                    'url' => '/women/simple-shirt.html',
                    'price' => 29.95,
                    'final_price' => 24.95,
                    'currency' => 'USD',
                    'short_description' => 'Lightweight cotton shirt for everyday product detail checks.',
                    'description' => 'Safe fixture shirt copy with deterministic detail fields for UI rendering.',
                    'meta_title' => 'Simple Shirt',
                    'meta_description' => 'Simple shirt product detail fixture.',
                    'visibility' => 'Catalog, Search',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 24,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.5,
                        'reviews_count' => 12,
                    ],
                    'category_ids' => [2001],
                    'custom_options' => [
                        [
                            'code' => 'monogram',
                            'title' => 'Monogram',
                            'type' => 'field',
                            'is_required' => false,
                            'price' => 5.00,
                        ],
                    ],
                    'related_skus' => ['configurable-hoodie'],
                    'upsell_skus' => ['configurable-hoodie'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7001],
                    'downloadable_entity_ids' => [8001],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'name' => 'Configurable Hoodie',
                    'type' => 'configurable',
                    'attribute_set' => 'Default',
                    'url_key' => 'configurable-hoodie',
                    'url' => '/gear/configurable-hoodie.html',
                    'price' => 59.00,
                    'final_price' => 59.00,
                    'currency' => 'USD',
                    'short_description' => 'Configurable hoodie with size and color selections.',
                    'description' => 'Safe fixture hoodie copy for configurable product detail rendering.',
                    'meta_title' => 'Configurable Hoodie',
                    'meta_description' => 'Configurable hoodie product detail fixture.',
                    'visibility' => 'Catalog, Search',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 8,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.8,
                        'reviews_count' => 18,
                    ],
                    'category_ids' => [2002],
                    'configurable_options' => [
                        [
                            'attribute_code' => 'size',
                            'label' => 'Size',
                            'values' => ['S', 'M', 'L'],
                        ],
                        [
                            'attribute_code' => 'color',
                            'label' => 'Color',
                            'values' => ['Black', 'Gray'],
                        ],
                    ],
                    'variants' => [
                        [
                            'sku' => 'configurable-hoodie-black-m',
                            'attributes' => ['color' => 'Black', 'size' => 'M'],
                            'price' => 59.00,
                            'is_in_stock' => true,
                        ],
                    ],
                    'related_skus' => ['simple-shirt'],
                    'upsell_skus' => ['simple-shirt'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7002],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3003,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'name' => 'Einfaches Hemd',
                    'type' => 'simple',
                    'attribute_set' => 'Default',
                    'url_key' => 'einfaches-hemd',
                    'url' => '/de/damen/einfaches-hemd.html',
                    'price' => 31.95,
                    'final_price' => 26.95,
                    'currency' => 'EUR',
                    'short_description' => 'Lokalisierte Produktdetail-Zeile fuer ein einfaches Hemd.',
                    'description' => 'Sichere Fixture-Beschreibung fuer die Produktdetailansicht.',
                    'meta_title' => 'Einfaches Hemd',
                    'meta_description' => 'Produktdetail-Fixture fuer ein einfaches Hemd.',
                    'visibility' => 'Katalog, Suche',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 18,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.5,
                        'reviews_count' => 9,
                    ],
                    'category_ids' => [2001],
                    'custom_options' => [
                        [
                            'code' => 'monogram',
                            'title' => 'Monogramm',
                            'type' => 'field',
                            'is_required' => false,
                            'price' => 5.00,
                        ],
                    ],
                    'related_skus' => ['configurable-hoodie'],
                    'upsell_skus' => ['configurable-hoodie'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7003],
                    'downloadable_entity_ids' => [8002],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3004,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'name' => 'Konfigurierbarer Hoodie',
                    'type' => 'configurable',
                    'attribute_set' => 'Default',
                    'url_key' => 'konfigurierbarer-hoodie',
                    'url' => '/de/ausruestung/konfigurierbarer-hoodie.html',
                    'price' => 61.00,
                    'final_price' => 61.00,
                    'currency' => 'EUR',
                    'short_description' => 'Konfigurierbarer Hoodie mit Groessen- und Farbauswahl.',
                    'description' => 'Sichere Fixture-Beschreibung fuer konfigurierbare Produktdetails.',
                    'meta_title' => 'Konfigurierbarer Hoodie',
                    'meta_description' => 'Produktdetail-Fixture fuer einen konfigurierbaren Hoodie.',
                    'visibility' => 'Katalog, Suche',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 6,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.7,
                        'reviews_count' => 11,
                    ],
                    'category_ids' => [2002],
                    'configurable_options' => [
                        [
                            'attribute_code' => 'size',
                            'label' => 'Groesse',
                            'values' => ['S', 'M', 'L'],
                        ],
                        [
                            'attribute_code' => 'color',
                            'label' => 'Farbe',
                            'values' => ['Schwarz', 'Grau'],
                        ],
                    ],
                    'variants' => [
                        [
                            'sku' => 'configurable-hoodie-black-m',
                            'attributes' => ['color' => 'Schwarz', 'size' => 'M'],
                            'price' => 61.00,
                            'is_in_stock' => true,
                        ],
                    ],
                    'related_skus' => ['simple-shirt'],
                    'upsell_skus' => ['simple-shirt'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7004],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'base_image' => 'catalog/product/simple-shirt/main.jpg',
                    'small_image' => 'catalog/product/simple-shirt/small.jpg',
                    'thumbnail' => 'catalog/product/simple-shirt/thumb.jpg',
                    'missing_media' => false,
                    'gallery' => [
                        [
                            'file' => 'catalog/product/simple-shirt/main.jpg',
                            'label' => 'Simple Shirt front',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                        [
                            'file' => 'catalog/product/simple-shirt/detail.jpg',
                            'label' => 'Simple Shirt detail',
                            'position' => 2,
                            'disabled' => false,
                            'types' => [],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'base_image' => 'catalog/product/configurable-hoodie/main.jpg',
                    'small_image' => 'catalog/product/configurable-hoodie/small.jpg',
                    'thumbnail' => 'catalog/product/configurable-hoodie/thumb.jpg',
                    'missing_media' => true,
                    'missing_files' => ['catalog/product/configurable-hoodie/missing-swatch.jpg'],
                    'gallery' => [
                        [
                            'file' => 'catalog/product/configurable-hoodie/main.jpg',
                            'label' => 'Configurable Hoodie front',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7003,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'base_image' => 'catalog/product/simple-shirt/main.jpg',
                    'small_image' => 'catalog/product/simple-shirt/small.jpg',
                    'thumbnail' => 'catalog/product/simple-shirt/thumb.jpg',
                    'missing_media' => false,
                    'gallery' => [
                        [
                            'file' => 'catalog/product/simple-shirt/main.jpg',
                            'label' => 'Einfaches Hemd Vorderseite',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7004,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'base_image' => 'catalog/product/configurable-hoodie/main.jpg',
                    'small_image' => 'catalog/product/configurable-hoodie/small.jpg',
                    'thumbnail' => 'catalog/product/configurable-hoodie/thumb.jpg',
                    'missing_media' => true,
                    'missing_files' => ['catalog/product/configurable-hoodie/missing-swatch.jpg'],
                    'gallery' => [
                        [
                            'file' => 'catalog/product/configurable-hoodie/main.jpg',
                            'label' => 'Konfigurierbarer Hoodie Vorderseite',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'shirt',
                    'filters' => [],
                    'results_count' => 1,
                    'result_skus' => ['simple-shirt'],
                    'redirect' => null,
                    'synonyms' => ['top', 'tee'],
                    'canonical_url' => '/catalogsearch/result/?q=shirt',
                    'rss_url' => '/rss/catalog/notifystock/?q=shirt',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'query_type' => 'advanced',
                    'query' => 'hoodie under 60',
                    'filters' => [
                        'category' => 'Gear',
                        'price' => ['from' => 0, 'to' => 60],
                        'visibility' => 'Catalog, Search',
                    ],
                    'results_count' => 1,
                    'result_skus' => ['configurable-hoodie'],
                    'redirect' => null,
                    'synonyms' => ['sweatshirt', 'pullover'],
                    'canonical_url' => '/catalogsearch/advanced/result/?category=gear&price[to]=60&q=hoodie',
                    'rss_url' => '/rss/catalog/special/?q=hoodie',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4003,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'legacy jacket',
                    'filters' => [],
                    'results_count' => 0,
                    'result_skus' => [],
                    'redirect' => [
                        'target' => '/gear/configurable-hoodie.html',
                        'type' => 302,
                        'reason' => 'search synonym redirect',
                    ],
                    'synonyms' => ['hoodie', 'sweatshirt'],
                    'canonical_url' => '/catalogsearch/result/?q=legacy+jacket',
                    'rss_url' => '/rss/catalog/notifystock/?q=legacy+jacket',
                    'is_index_stale' => true,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4004,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'hemd',
                    'filters' => [],
                    'results_count' => 1,
                    'result_skus' => ['simple-shirt'],
                    'redirect' => null,
                    'synonyms' => ['shirt', 'oberteil'],
                    'canonical_url' => '/de/catalogsearch/result/?q=hemd',
                    'rss_url' => '/de/rss/catalog/notifystock/?q=hemd',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4005,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'query_type' => 'advanced',
                    'query' => 'hoodie bis 65',
                    'filters' => [
                        'category' => 'Ausrustung',
                        'price' => ['from' => 0, 'to' => 65],
                        'visibility' => 'Katalog, Suche',
                    ],
                    'results_count' => 1,
                    'result_skus' => ['configurable-hoodie'],
                    'redirect' => null,
                    'synonyms' => ['kapuzenpullover', 'pullover'],
                    'canonical_url' => '/de/catalogsearch/advanced/result/?category=ausrustung&price[to]=65&q=hoodie',
                    'rss_url' => '/de/rss/catalog/special/?q=hoodie',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4006,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'winterjacke',
                    'filters' => [],
                    'results_count' => 0,
                    'result_skus' => [],
                    'redirect' => [
                        'target' => '/de/ausrustung/konfigurierbarer-hoodie.html',
                        'type' => 302,
                        'reason' => 'search synonym redirect',
                    ],
                    'synonyms' => ['hoodie', 'kapuzenpullover'],
                    'canonical_url' => '/de/catalogsearch/result/?q=winterjacke',
                    'rss_url' => '/de/rss/catalog/notifystock/?q=winterjacke',
                    'is_index_stale' => true,
                ]),
            ],
            [
                'feature_key' => 'customer',
                'entity_id' => 5001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'customer_id' => 5001,
                    'email' => 'maria.sommer@example.test',
                    'firstname' => 'Maria',
                    'lastname' => 'Sommer',
                    'full_name' => 'Maria Sommer',
                    'group' => 'General',
                    'is_active' => true,
                    'created_at' => '2026-01-15T10:30:00+00:00',
                    'last_login_at' => '2026-05-10T08:15:00+00:00',
                    'orders_count' => 3,
                    'lifetime_value' => 184.70,
                    'newsletter_subscribed' => true,
                    'default_billing_address_id' => 6001,
                    'default_shipping_address_id' => 6001,
                ]),
            ],
            [
                'feature_key' => 'customer',
                'entity_id' => 5002,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'customer_id' => 5002,
                    'email' => 'lena.keller@example.test',
                    'firstname' => 'Lena',
                    'lastname' => 'Keller',
                    'full_name' => 'Lena Keller',
                    'group' => 'Retail Kunde',
                    'is_active' => true,
                    'created_at' => '2026-02-20T11:45:00+00:00',
                    'last_login_at' => '2026-05-12T07:20:00+00:00',
                    'orders_count' => 2,
                    'lifetime_value' => 129.90,
                    'newsletter_subscribed' => false,
                    'default_billing_address_id' => 6002,
                    'default_shipping_address_id' => 6002,
                ]),
            ],
            [
                'feature_key' => 'customer_address',
                'entity_id' => 6001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'address_id' => 6001,
                    'customer_id' => 5001,
                    'address_type' => 'billing_shipping',
                    'firstname' => 'Maria',
                    'lastname' => 'Sommer',
                    'company' => 'Example Retail LLC',
                    'street' => ['101 Market Street', 'Suite 400'],
                    'city' => 'Portland',
                    'region' => 'Oregon',
                    'postcode' => '97204',
                    'country_id' => 'US',
                    'telephone' => '+1-503-555-0198',
                    'is_default_billing' => true,
                    'is_default_shipping' => true,
                    'formatted_lines' => [
                        'Maria Sommer',
                        'Example Retail LLC',
                        '101 Market Street, Suite 400',
                        'Portland, Oregon 97204',
                        'US',
                    ],
                ]),
            ],
            [
                'feature_key' => 'customer_address',
                'entity_id' => 6002,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'address_id' => 6002,
                    'customer_id' => 5002,
                    'address_type' => 'billing_shipping',
                    'firstname' => 'Lena',
                    'lastname' => 'Keller',
                    'company' => 'Beispiel Handel GmbH',
                    'street' => ['Friedrichstrasse 40'],
                    'city' => 'Berlin',
                    'region' => 'Berlin',
                    'postcode' => '10117',
                    'country_id' => 'DE',
                    'telephone' => '+49-30-5550198',
                    'is_default_billing' => true,
                    'is_default_shipping' => true,
                    'formatted_lines' => [
                        'Lena Keller',
                        'Beispiel Handel GmbH',
                        'Friedrichstrasse 40',
                        '10117 Berlin',
                        'DE',
                    ],
                ]),
            ],
            [
                'feature_key' => 'wishlist',
                'entity_id' => 9101,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'wishlist_id' => 9101,
                    'customer_id' => 5001,
                    'customer_email' => 'maria.sommer@example.test',
                    'state' => 'shared',
                    'visibility' => 'shared_link',
                    'sharing_code' => 'wl-default-maria-001',
                    'shared_at' => '2026-05-01T12:00:00+00:00',
                    'message' => 'Safe shared wishlist fixture.',
                    'items_count' => 2,
                    'visible_product_skus' => ['simple-shirt', 'configurable-hoodie'],
                    'items' => [
                        [
                            'item_id' => 1,
                            'sku' => 'simple-shirt',
                            'qty' => 1,
                            'description' => 'Everyday shirt option.',
                            'added_at' => '2026-04-20T09:00:00+00:00',
                        ],
                        [
                            'item_id' => 2,
                            'sku' => 'configurable-hoodie',
                            'qty' => 1,
                            'description' => 'Warm hoodie option.',
                            'added_at' => '2026-04-21T09:00:00+00:00',
                        ],
                    ],
                    'can_move_to_cart' => true,
                    'denied_reason' => null,
                ]),
            ],
            [
                'feature_key' => 'wishlist',
                'entity_id' => 9102,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'wishlist_id' => 9102,
                    'customer_id' => 5001,
                    'customer_email' => 'maria.sommer@example.test',
                    'state' => 'empty_private',
                    'visibility' => 'owner_only',
                    'sharing_code' => null,
                    'shared_at' => null,
                    'message' => null,
                    'items_count' => 0,
                    'visible_product_skus' => [],
                    'items' => [],
                    'can_move_to_cart' => false,
                    'denied_reason' => 'not_shared',
                ]),
            ],
            [
                'feature_key' => 'wishlist',
                'entity_id' => 9103,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'wishlist_id' => 9103,
                    'customer_id' => 5002,
                    'customer_email' => 'lena.keller@example.test',
                    'state' => 'shared',
                    'visibility' => 'shared_link',
                    'sharing_code' => 'wl-de-lena-001',
                    'shared_at' => '2026-05-02T12:00:00+00:00',
                    'message' => 'Sichere geteilte Wunschlisten-Fixture.',
                    'items_count' => 1,
                    'visible_product_skus' => ['simple-shirt'],
                    'items' => [
                        [
                            'item_id' => 1,
                            'sku' => 'simple-shirt',
                            'qty' => 1,
                            'description' => 'Lokalisierte Hemd-Auswahl.',
                            'added_at' => '2026-04-22T09:00:00+00:00',
                        ],
                    ],
                    'can_move_to_cart' => true,
                    'denied_reason' => null,
                ]),
            ],
            [
                'feature_key' => 'compare',
                'entity_id' => 9201,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'compare_id' => 9201,
                    'customer_id' => 5001,
                    'state' => 'active',
                    'items_count' => 2,
                    'visible_product_skus' => ['simple-shirt', 'configurable-hoodie'],
                    'attributes' => [
                        [
                            'code' => 'price',
                            'label' => 'Price',
                            'values' => [
                                'simple-shirt' => 29.95,
                                'configurable-hoodie' => 59.00,
                            ],
                        ],
                        [
                            'code' => 'color',
                            'label' => 'Color',
                            'values' => [
                                'simple-shirt' => 'Blue',
                                'configurable-hoodie' => 'Black',
                            ],
                        ],
                        [
                            'code' => 'stock_status',
                            'label' => 'Stock Status',
                            'values' => [
                                'simple-shirt' => 'In Stock',
                                'configurable-hoodie' => 'In Stock',
                            ],
                        ],
                    ],
                    'denied_reason' => null,
                ]),
            ],
            [
                'feature_key' => 'compare',
                'entity_id' => 9202,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'compare_id' => 9202,
                    'customer_id' => null,
                    'state' => 'empty_guest',
                    'items_count' => 0,
                    'visible_product_skus' => [],
                    'attributes' => [],
                    'denied_reason' => 'guest_session_expired',
                ]),
            ],
            [
                'feature_key' => 'compare',
                'entity_id' => 9203,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'compare_id' => 9203,
                    'customer_id' => 5002,
                    'state' => 'active',
                    'items_count' => 2,
                    'visible_product_skus' => ['simple-shirt', 'configurable-hoodie'],
                    'attributes' => [
                        [
                            'code' => 'price',
                            'label' => 'Preis',
                            'values' => [
                                'simple-shirt' => 31.95,
                                'configurable-hoodie' => 61.00,
                            ],
                        ],
                        [
                            'code' => 'color',
                            'label' => 'Farbe',
                            'values' => [
                                'simple-shirt' => 'Blau',
                                'configurable-hoodie' => 'Schwarz',
                            ],
                        ],
                    ],
                    'denied_reason' => null,
                ]),
            ],
            [
                'feature_key' => 'review',
                'entity_id' => 9301,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'review_id' => 9301,
                    'product_sku' => 'simple-shirt',
                    'customer_id' => 5001,
                    'customer_email' => 'maria.sommer@example.test',
                    'nickname' => 'Maria S.',
                    'title' => 'Reliable shirt',
                    'detail' => 'Safe fixture review for approved storefront display.',
                    'status' => 'approved',
                    'is_visible' => true,
                    'moderation' => [
                        'status' => 'approved',
                        'moderated_by' => 'admin@example.test',
                        'moderated_at' => '2026-05-03T10:00:00+00:00',
                    ],
                    'ratings' => [
                        'quality' => 5,
                        'value' => 4,
                        'price' => 4,
                    ],
                    'average_rating' => 4.3,
                    'created_at' => '2026-04-25T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'review',
                'entity_id' => 9302,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'review_id' => 9302,
                    'product_sku' => 'configurable-hoodie',
                    'customer_id' => 5001,
                    'customer_email' => 'maria.sommer@example.test',
                    'nickname' => 'Maria S.',
                    'title' => 'Awaiting moderation',
                    'detail' => 'Safe pending review fixture.',
                    'status' => 'pending',
                    'is_visible' => false,
                    'moderation' => [
                        'status' => 'pending',
                        'moderated_by' => null,
                        'moderated_at' => null,
                    ],
                    'ratings' => [
                        'quality' => 4,
                        'value' => 4,
                        'price' => 3,
                    ],
                    'average_rating' => 3.7,
                    'created_at' => '2026-04-26T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'review',
                'entity_id' => 9303,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'review_id' => 9303,
                    'product_sku' => 'simple-shirt',
                    'customer_id' => 5002,
                    'customer_email' => 'lena.keller@example.test',
                    'nickname' => 'Lena K.',
                    'title' => 'Zuverlaessiges Hemd',
                    'detail' => 'Sichere genehmigte Bewertungs-Fixture.',
                    'status' => 'approved',
                    'is_visible' => true,
                    'moderation' => [
                        'status' => 'approved',
                        'moderated_by' => 'admin@example.test',
                        'moderated_at' => '2026-05-04T10:00:00+00:00',
                    ],
                    'ratings' => [
                        'quality' => 5,
                        'value' => 5,
                        'price' => 4,
                    ],
                    'average_rating' => 4.7,
                    'created_at' => '2026-04-27T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'tag',
                'entity_id' => 9401,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'tag_id' => 9401,
                    'product_sku' => 'simple-shirt',
                    'customer_id' => 5001,
                    'name' => 'summer',
                    'status' => 'approved',
                    'is_visible' => true,
                    'uses_count' => 6,
                    'related_product_skus' => ['simple-shirt'],
                    'created_at' => '2026-04-28T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'tag',
                'entity_id' => 9402,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'tag_id' => 9402,
                    'product_sku' => 'configurable-hoodie',
                    'customer_id' => 5001,
                    'name' => 'needs-review',
                    'status' => 'pending',
                    'is_visible' => false,
                    'uses_count' => 1,
                    'related_product_skus' => ['configurable-hoodie'],
                    'created_at' => '2026-04-29T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'tag',
                'entity_id' => 9403,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'tag_id' => 9403,
                    'product_sku' => 'simple-shirt',
                    'customer_id' => 5002,
                    'name' => 'sommer',
                    'status' => 'approved',
                    'is_visible' => true,
                    'uses_count' => 3,
                    'related_product_skus' => ['simple-shirt'],
                    'created_at' => '2026-04-30T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_page',
                'entity_id' => 10001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'page_id' => 10001,
                    'identifier' => 'about-us',
                    'title' => 'About Us',
                    'heading' => 'About Example Store',
                    'status' => 'active',
                    'is_active' => true,
                    'is_home_page' => false,
                    'is_no_route' => false,
                    'is_404' => false,
                    'http_status' => 200,
                    'layout' => '1column',
                    'content_heading' => 'About Example Store',
                    'content_preview' => 'Safe CMS page fixture for storefront content rendering.',
                    'block_identifiers' => ['home-page-hero', 'footer-links'],
                    'widget_instance_ids' => [10201],
                    'meta_title' => 'About Us | Example Store',
                    'meta_description' => 'Learn about the default store view.',
                    'canonical_url' => '/about-us',
                    'request_path' => 'about-us',
                    'target_path' => 'cms/page/view/page_id/10001',
                    'redirect' => null,
                    'updated_at' => '2026-05-16T09:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_page',
                'entity_id' => 10002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'page_id' => 10002,
                    'identifier' => 'spring-sale-legacy',
                    'title' => 'Spring Sale Legacy',
                    'heading' => 'Retired Spring Sale',
                    'status' => 'disabled',
                    'is_active' => false,
                    'is_home_page' => false,
                    'is_no_route' => false,
                    'is_404' => false,
                    'http_status' => 301,
                    'layout' => '1column',
                    'content_heading' => 'Retired Spring Sale',
                    'content_preview' => 'Disabled CMS campaign page retained for redirect checks.',
                    'block_identifiers' => ['footer-links'],
                    'widget_instance_ids' => [],
                    'meta_title' => 'Spring Sale Legacy',
                    'meta_description' => 'Disabled campaign page fixture.',
                    'canonical_url' => null,
                    'request_path' => 'spring-sale-legacy',
                    'target_path' => 'cms/page/view/page_id/10002',
                    'redirect' => [
                        'target' => '/sale',
                        'type' => 301,
                        'reason' => 'campaign retired',
                    ],
                    'updated_at' => '2026-03-31T20:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_page',
                'entity_id' => 10003,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'page_id' => 10003,
                    'identifier' => 'no-route',
                    'title' => '404 Not Found',
                    'heading' => 'Page Not Found',
                    'status' => 'active',
                    'is_active' => true,
                    'is_home_page' => false,
                    'is_no_route' => true,
                    'is_404' => true,
                    'http_status' => 404,
                    'layout' => '1column',
                    'content_heading' => 'Page Not Found',
                    'content_preview' => 'Default no-route CMS page fixture.',
                    'block_identifiers' => ['footer-links'],
                    'widget_instance_ids' => [],
                    'meta_title' => '404 Not Found',
                    'meta_description' => 'No-route storefront page fixture.',
                    'canonical_url' => '/no-route',
                    'request_path' => 'no-route',
                    'target_path' => 'cms/index/noRoute',
                    'redirect' => null,
                    'updated_at' => '2026-05-12T11:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_page',
                'entity_id' => 10004,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'page_id' => 10004,
                    'identifier' => 'ueber-uns',
                    'title' => 'Ueber Uns',
                    'heading' => 'Ueber Example Store',
                    'status' => 'active',
                    'is_active' => true,
                    'is_home_page' => false,
                    'is_no_route' => false,
                    'is_404' => false,
                    'http_status' => 200,
                    'layout' => '1column',
                    'content_heading' => 'Ueber Example Store',
                    'content_preview' => 'Lokalisierte CMS-Seite fuer Storefront-Inhalte.',
                    'block_identifiers' => ['home-page-hero-de', 'footer-links-de'],
                    'widget_instance_ids' => [10203],
                    'meta_title' => 'Ueber Uns | Example Store',
                    'meta_description' => 'Lokalisierte Ueber-uns-Seite.',
                    'canonical_url' => '/de/ueber-uns',
                    'request_path' => 'de/ueber-uns',
                    'target_path' => 'cms/page/view/page_id/10004',
                    'redirect' => null,
                    'updated_at' => '2026-05-16T10:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_page',
                'entity_id' => 10005,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'page_id' => 10005,
                    'identifier' => 'fruehlingsaktion-alt',
                    'title' => 'Fruehlingsaktion Alt',
                    'heading' => 'Beendete Fruehlingsaktion',
                    'status' => 'disabled',
                    'is_active' => false,
                    'is_home_page' => false,
                    'is_no_route' => false,
                    'is_404' => false,
                    'http_status' => 301,
                    'layout' => '1column',
                    'content_heading' => 'Beendete Fruehlingsaktion',
                    'content_preview' => 'Deaktivierte CMS-Kampagne fuer Redirect-Pruefungen.',
                    'block_identifiers' => ['footer-links-de'],
                    'widget_instance_ids' => [],
                    'meta_title' => 'Fruehlingsaktion Alt',
                    'meta_description' => 'Deaktivierte Kampagnen-Fixture.',
                    'canonical_url' => null,
                    'request_path' => 'de/fruehlingsaktion-alt',
                    'target_path' => 'cms/page/view/page_id/10005',
                    'redirect' => [
                        'target' => '/de/angebote',
                        'type' => 301,
                        'reason' => 'campaign retired',
                    ],
                    'updated_at' => '2026-03-31T21:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_page',
                'entity_id' => 10006,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'page_id' => 10006,
                    'identifier' => 'no-route-de',
                    'title' => 'Seite Nicht Gefunden',
                    'heading' => 'Seite Nicht Gefunden',
                    'status' => 'active',
                    'is_active' => true,
                    'is_home_page' => false,
                    'is_no_route' => true,
                    'is_404' => true,
                    'http_status' => 404,
                    'layout' => '1column',
                    'content_heading' => 'Seite Nicht Gefunden',
                    'content_preview' => 'Lokalisierte No-Route-CMS-Seite.',
                    'block_identifiers' => ['footer-links-de'],
                    'widget_instance_ids' => [],
                    'meta_title' => 'Seite Nicht Gefunden',
                    'meta_description' => 'Lokalisierte No-Route-Fixture.',
                    'canonical_url' => '/de/no-route',
                    'request_path' => 'de/no-route',
                    'target_path' => 'cms/index/noRoute',
                    'redirect' => null,
                    'updated_at' => '2026-05-12T12:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_block',
                'entity_id' => 10101,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'block_id' => 10101,
                    'identifier' => 'home-page-hero',
                    'title' => 'Home Page Hero',
                    'is_active' => true,
                    'content_preview' => 'Default hero block with safe WYSIWYG media reference.',
                    'wysiwyg_media' => ['wysiwyg/home/default-hero.jpg'],
                    'used_on' => ['cms_page:about-us'],
                    'cache_tags' => ['cms_b_10101', 'store_9001'],
                    'updated_at' => '2026-05-15T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_block',
                'entity_id' => 10102,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'block_id' => 10102,
                    'identifier' => 'footer-links',
                    'title' => 'Footer Links',
                    'is_active' => true,
                    'content_preview' => 'Default footer navigation block fixture.',
                    'wysiwyg_media' => [],
                    'used_on' => ['cms_page:about-us', 'cms_page:no-route'],
                    'cache_tags' => ['cms_b_10102', 'store_9001'],
                    'updated_at' => '2026-05-14T08:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_block',
                'entity_id' => 10103,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'block_id' => 10103,
                    'identifier' => 'home-page-hero-de',
                    'title' => 'Startseiten-Hero',
                    'is_active' => true,
                    'content_preview' => 'Lokalisierter Hero-Block mit WYSIWYG-Medienreferenz.',
                    'wysiwyg_media' => ['wysiwyg/home/de-hero.jpg'],
                    'used_on' => ['cms_page:ueber-uns'],
                    'cache_tags' => ['cms_b_10103', 'store_9002'],
                    'updated_at' => '2026-05-15T09:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'cms_block',
                'entity_id' => 10104,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'block_id' => 10104,
                    'identifier' => 'footer-links-de',
                    'title' => 'Footer Links DE',
                    'is_active' => true,
                    'content_preview' => 'Lokalisierter Footer-Navigationsblock.',
                    'wysiwyg_media' => [],
                    'used_on' => ['cms_page:ueber-uns', 'cms_page:no-route-de'],
                    'cache_tags' => ['cms_b_10104', 'store_9002'],
                    'updated_at' => '2026-05-14T09:00:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'widget',
                'entity_id' => 10201,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'widget_instance_id' => 10201,
                    'type' => 'catalog/widget_new',
                    'title' => 'New Products Rail',
                    'is_active' => true,
                    'template' => 'product/widget/new/content/new_grid.phtml',
                    'page_groups' => ['cms_page:about-us'],
                    'sort_order' => 20,
                    'block_reference' => 'content',
                    'conditions' => [
                        'category_ids' => [2001, 2002],
                        'skus' => ['simple-shirt', 'configurable-hoodie'],
                    ],
                    'cache_lifetime' => 86400,
                    'updated_at' => '2026-05-13T08:30:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'widget',
                'entity_id' => 10202,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'widget_instance_id' => 10202,
                    'type' => 'cms/widget_block',
                    'title' => 'Retired Promo Block Widget',
                    'is_active' => false,
                    'template' => 'cms/widget/static_block/default.phtml',
                    'page_groups' => ['cms_page:spring-sale-legacy'],
                    'sort_order' => 10,
                    'block_reference' => 'content',
                    'conditions' => [
                        'block_identifier' => 'footer-links',
                    ],
                    'cache_lifetime' => 0,
                    'updated_at' => '2026-03-31T20:30:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'widget',
                'entity_id' => 10203,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'widget_instance_id' => 10203,
                    'type' => 'catalog/widget_new',
                    'title' => 'Neue Produkte',
                    'is_active' => true,
                    'template' => 'product/widget/new/content/new_grid.phtml',
                    'page_groups' => ['cms_page:ueber-uns'],
                    'sort_order' => 20,
                    'block_reference' => 'content',
                    'conditions' => [
                        'category_ids' => [2001, 2002],
                        'skus' => ['simple-shirt', 'configurable-hoodie'],
                    ],
                    'cache_lifetime' => 86400,
                    'updated_at' => '2026-05-13T09:30:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'widget',
                'entity_id' => 10204,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'widget_instance_id' => 10204,
                    'type' => 'cms/widget_block',
                    'title' => 'Deaktiviertes Promo-Block-Widget',
                    'is_active' => false,
                    'template' => 'cms/widget/static_block/default.phtml',
                    'page_groups' => ['cms_page:fruehlingsaktion-alt'],
                    'sort_order' => 10,
                    'block_reference' => 'content',
                    'conditions' => [
                        'block_identifier' => 'footer-links-de',
                    ],
                    'cache_lifetime' => 0,
                    'updated_at' => '2026-03-31T21:30:00+00:00',
                ]),
            ],
            [
                'feature_key' => 'sitemap',
                'entity_id' => 10301,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sitemap_id' => 10301,
                    'type' => 'sitemap',
                    'file' => 'sitemap.xml',
                    'url' => '/sitemap.xml',
                    'is_fresh' => true,
                    'generated_at' => '2026-05-18T02:05:00+00:00',
                    'ttl_minutes' => 1440,
                    'url_count' => 42,
                    'included_features' => ['cms_page', 'category', 'product'],
                    'robots_entry' => true,
                    'rss' => [
                        'feed_url' => '/rss/catalog/new',
                        'is_fresh' => true,
                        'generated_at' => '2026-05-18T02:10:00+00:00',
                        'items_count' => 12,
                    ],
                ]),
            ],
            [
                'feature_key' => 'sitemap',
                'entity_id' => 10302,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sitemap_id' => 10302,
                    'type' => 'rss',
                    'file' => 'rss/catalog/special.xml',
                    'url' => '/rss/catalog/special',
                    'is_fresh' => false,
                    'generated_at' => '2026-05-15T02:10:00+00:00',
                    'ttl_minutes' => 360,
                    'items_count' => 5,
                    'stale_reason' => 'catalog price rule updated after feed generation',
                    'related_sitemap_id' => 10301,
                ]),
            ],
            [
                'feature_key' => 'sitemap',
                'entity_id' => 10303,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sitemap_id' => 10303,
                    'type' => 'sitemap',
                    'file' => 'de/sitemap.xml',
                    'url' => '/de/sitemap.xml',
                    'is_fresh' => true,
                    'generated_at' => '2026-05-18T02:20:00+00:00',
                    'ttl_minutes' => 1440,
                    'url_count' => 39,
                    'included_features' => ['cms_page', 'category', 'product'],
                    'robots_entry' => true,
                    'rss' => [
                        'feed_url' => '/de/rss/catalog/new',
                        'is_fresh' => true,
                        'generated_at' => '2026-05-18T02:25:00+00:00',
                        'items_count' => 9,
                    ],
                ]),
            ],
            [
                'feature_key' => 'sitemap',
                'entity_id' => 10304,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sitemap_id' => 10304,
                    'type' => 'rss',
                    'file' => 'de/rss/catalog/special.xml',
                    'url' => '/de/rss/catalog/special',
                    'is_fresh' => false,
                    'generated_at' => '2026-05-15T02:25:00+00:00',
                    'ttl_minutes' => 360,
                    'items_count' => 4,
                    'stale_reason' => 'localized CMS page updated after feed generation',
                    'related_sitemap_id' => 10303,
                ]),
            ],
            [
                'feature_key' => 'url_rewrite',
                'entity_id' => 10401,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'url_rewrite_id' => 10401,
                    'entity_type' => 'cms-page',
                    'entity_id' => 10001,
                    'request_path' => 'about-us',
                    'target_path' => 'cms/page/view/page_id/10001',
                    'redirect_type' => 0,
                    'is_autogenerated' => false,
                    'canonical_url' => '/about-us',
                    'metadata' => [
                        'store_scoped' => true,
                        'source' => 'cms_page',
                        'meta_robots' => 'INDEX,FOLLOW',
                        'preserve_query' => false,
                    ],
                ]),
            ],
            [
                'feature_key' => 'url_rewrite',
                'entity_id' => 10402,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'url_rewrite_id' => 10402,
                    'entity_type' => 'custom',
                    'entity_id' => 10001,
                    'request_path' => 'company',
                    'target_path' => 'about-us',
                    'redirect_type' => 301,
                    'is_autogenerated' => false,
                    'canonical_url' => '/about-us',
                    'metadata' => [
                        'store_scoped' => true,
                        'source' => 'admin_redirect',
                        'reason' => 'cms identifier changed',
                        'preserve_query' => true,
                    ],
                ]),
            ],
            [
                'feature_key' => 'url_rewrite',
                'entity_id' => 10403,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'url_rewrite_id' => 10403,
                    'entity_type' => 'cms-page',
                    'entity_id' => 10004,
                    'request_path' => 'de/ueber-uns',
                    'target_path' => 'cms/page/view/page_id/10004',
                    'redirect_type' => 0,
                    'is_autogenerated' => false,
                    'canonical_url' => '/de/ueber-uns',
                    'metadata' => [
                        'store_scoped' => true,
                        'source' => 'cms_page',
                        'meta_robots' => 'INDEX,FOLLOW',
                        'preserve_query' => false,
                    ],
                ]),
            ],
            [
                'feature_key' => 'url_rewrite',
                'entity_id' => 10404,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'url_rewrite_id' => 10404,
                    'entity_type' => 'custom',
                    'entity_id' => 10004,
                    'request_path' => 'de/unternehmen',
                    'target_path' => 'de/ueber-uns',
                    'redirect_type' => 301,
                    'is_autogenerated' => false,
                    'canonical_url' => '/de/ueber-uns',
                    'metadata' => [
                        'store_scoped' => true,
                        'source' => 'admin_redirect',
                        'reason' => 'localized cms identifier changed',
                        'preserve_query' => true,
                    ],
                ]),
            ],
            [
                'feature_key' => 'store_scope',
                'entity_id' => 10501,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'website_code' => 'base',
                    'store_group_code' => 'main_website_store',
                    'store_code' => 'default',
                    'store_name' => 'Default Store View',
                    'locale' => 'en_US',
                    'currency' => 'USD',
                    'base_url' => 'https://example.test/',
                    'secure_base_url' => 'https://example.test/',
                    'cms_home_page' => 'home',
                    'cms_no_route' => 'no-route',
                    'default_title' => 'Example Store',
                    'can_use_default' => true,
                    'config' => [
                        'web/seo/use_rewrites' => true,
                        'cms/wysiwyg/enabled' => true,
                        'sitemap/generate/enabled' => true,
                        'rss/config/active' => true,
                    ],
                ]),
            ],
            [
                'feature_key' => 'store_scope',
                'entity_id' => 10502,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'website_code' => 'base',
                    'store_group_code' => 'main_website_store',
                    'store_code' => 'de',
                    'store_name' => 'German Store View',
                    'locale' => 'de_DE',
                    'currency' => 'EUR',
                    'base_url' => 'https://example.test/de/',
                    'secure_base_url' => 'https://example.test/de/',
                    'cms_home_page' => 'home-de',
                    'cms_no_route' => 'no-route-de',
                    'default_title' => 'Example Store DE',
                    'can_use_default' => false,
                    'config' => [
                        'web/seo/use_rewrites' => true,
                        'cms/wysiwyg/enabled' => true,
                        'sitemap/generate/enabled' => true,
                        'rss/config/active' => true,
                    ],
                ]),
            ],
            [
                'feature_key' => 'downloadable',
                'entity_id' => 8001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'downloadable-size-guide',
                    'title' => 'Size Guide PDF',
                    'file' => 'downloadable/files/size-guide.pdf',
                    'sample_file' => 'downloadable/samples/size-guide-sample.pdf',
                    'is_shareable' => false,
                    'requires_login' => true,
                    'permission' => 'customer_account_purchase',
                    'customer_group_permissions' => ['General'],
                    'max_downloads' => 5,
                    'related_product_skus' => ['simple-shirt', 'configurable-hoodie'],
                ]),
            ],
            [
                'feature_key' => 'downloadable',
                'entity_id' => 8002,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'downloadable-size-guide',
                    'title' => 'Groessentabelle PDF',
                    'file' => 'downloadable/files/size-guide.pdf',
                    'sample_file' => 'downloadable/samples/size-guide-sample.pdf',
                    'is_shareable' => false,
                    'requires_login' => true,
                    'permission' => 'customer_account_purchase',
                    'customer_group_permissions' => ['Retail Kunde'],
                    'max_downloads' => 5,
                    'related_product_skus' => ['simple-shirt', 'configurable-hoodie'],
                ]),
            ],
        ]);
    }
}
