<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DomainFactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('domain_facts')
            ->whereIn('feature_key', ['catalog', 'category', 'product', 'product_media', 'search', 'customer', 'customer_address', 'downloadable'])
            ->whereIn('entity_id', [1001, 1002, 1003, 2001, 2002, 3001, 3002, 3003, 3004, 4001, 4002, 4003, 4004, 4005, 4006, 5001, 5002, 6001, 6002, 7001, 7002, 7003, 7004, 8001, 8002])
            ->whereIn('store_id', [9001, 9002])
            ->delete();

        DB::table('domain_facts')->insert([
            [
                'feature_key' => 'catalog',
                'entity_id' => 1001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Simple Shirt',
                    'sku' => 'simple-shirt',
                    'type' => 'simple',
                    'price' => 29.95,
                    'category' => 'Women',
                    'stock' => 24,
                    'url' => '/women/simple-shirt.html',
                    'short_description' => 'Lightweight cotton shirt for everyday catalog browsing.',
                    'swatch' => 'blue',
                    'rating' => 4.5,
                    'visibility' => 'Catalog, Search',
                ]),
            ],
            [
                'feature_key' => 'catalog',
                'entity_id' => 1002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Configurable Hoodie',
                    'sku' => 'configurable-hoodie',
                    'type' => 'configurable',
                    'price' => 59.00,
                    'category' => 'Gear',
                    'stock' => 8,
                    'url' => '/gear/configurable-hoodie.html',
                    'short_description' => 'Size and color configurable hoodie used for filter and sort checks.',
                    'swatch' => 'black',
                    'rating' => 4.8,
                    'visibility' => 'Catalog, Search',
                ]),
            ],
            [
                'feature_key' => 'catalog',
                'entity_id' => 1003,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'name' => 'Einfaches Hemd',
                    'sku' => 'simple-shirt',
                    'type' => 'simple',
                    'price' => 31.95,
                    'category' => 'Damen',
                    'stock' => 18,
                    'url' => '/de/damen/einfaches-hemd.html',
                    'short_description' => 'Lokalisierte Store-View-Zeile fuer Katalogpruefungen.',
                    'swatch' => 'blau',
                    'rating' => 4.5,
                    'visibility' => 'Katalog, Suche',
                ]),
            ],
            [
                'feature_key' => 'category',
                'entity_id' => 2001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Women',
                    'url_key' => 'women',
                    'is_active' => true,
                    'product_ids' => [3001],
                ]),
            ],
            [
                'feature_key' => 'category',
                'entity_id' => 2002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'name' => 'Gear',
                    'url_key' => 'gear',
                    'is_active' => true,
                    'product_ids' => [3002],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'name' => 'Simple Shirt',
                    'type' => 'simple',
                    'attribute_set' => 'Default',
                    'url_key' => 'simple-shirt',
                    'url' => '/women/simple-shirt.html',
                    'price' => 29.95,
                    'final_price' => 24.95,
                    'currency' => 'USD',
                    'short_description' => 'Lightweight cotton shirt for everyday product detail checks.',
                    'description' => 'Safe fixture shirt copy with deterministic detail fields for UI rendering.',
                    'meta_title' => 'Simple Shirt',
                    'meta_description' => 'Simple shirt product detail fixture.',
                    'visibility' => 'Catalog, Search',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 24,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.5,
                        'reviews_count' => 12,
                    ],
                    'category_ids' => [2001],
                    'custom_options' => [
                        [
                            'code' => 'monogram',
                            'title' => 'Monogram',
                            'type' => 'field',
                            'is_required' => false,
                            'price' => 5.00,
                        ],
                    ],
                    'related_skus' => ['configurable-hoodie'],
                    'upsell_skus' => ['configurable-hoodie'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7001],
                    'downloadable_entity_ids' => [8001],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'name' => 'Configurable Hoodie',
                    'type' => 'configurable',
                    'attribute_set' => 'Default',
                    'url_key' => 'configurable-hoodie',
                    'url' => '/gear/configurable-hoodie.html',
                    'price' => 59.00,
                    'final_price' => 59.00,
                    'currency' => 'USD',
                    'short_description' => 'Configurable hoodie with size and color selections.',
                    'description' => 'Safe fixture hoodie copy for configurable product detail rendering.',
                    'meta_title' => 'Configurable Hoodie',
                    'meta_description' => 'Configurable hoodie product detail fixture.',
                    'visibility' => 'Catalog, Search',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 8,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.8,
                        'reviews_count' => 18,
                    ],
                    'category_ids' => [2002],
                    'configurable_options' => [
                        [
                            'attribute_code' => 'size',
                            'label' => 'Size',
                            'values' => ['S', 'M', 'L'],
                        ],
                        [
                            'attribute_code' => 'color',
                            'label' => 'Color',
                            'values' => ['Black', 'Gray'],
                        ],
                    ],
                    'variants' => [
                        [
                            'sku' => 'configurable-hoodie-black-m',
                            'attributes' => ['color' => 'Black', 'size' => 'M'],
                            'price' => 59.00,
                            'is_in_stock' => true,
                        ],
                    ],
                    'related_skus' => ['simple-shirt'],
                    'upsell_skus' => ['simple-shirt'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7002],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3003,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'name' => 'Einfaches Hemd',
                    'type' => 'simple',
                    'attribute_set' => 'Default',
                    'url_key' => 'einfaches-hemd',
                    'url' => '/de/damen/einfaches-hemd.html',
                    'price' => 31.95,
                    'final_price' => 26.95,
                    'currency' => 'EUR',
                    'short_description' => 'Lokalisierte Produktdetail-Zeile fuer ein einfaches Hemd.',
                    'description' => 'Sichere Fixture-Beschreibung fuer die Produktdetailansicht.',
                    'meta_title' => 'Einfaches Hemd',
                    'meta_description' => 'Produktdetail-Fixture fuer ein einfaches Hemd.',
                    'visibility' => 'Katalog, Suche',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 18,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.5,
                        'reviews_count' => 9,
                    ],
                    'category_ids' => [2001],
                    'custom_options' => [
                        [
                            'code' => 'monogram',
                            'title' => 'Monogramm',
                            'type' => 'field',
                            'is_required' => false,
                            'price' => 5.00,
                        ],
                    ],
                    'related_skus' => ['configurable-hoodie'],
                    'upsell_skus' => ['configurable-hoodie'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7003],
                    'downloadable_entity_ids' => [8002],
                ]),
            ],
            [
                'feature_key' => 'product',
                'entity_id' => 3004,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'name' => 'Konfigurierbarer Hoodie',
                    'type' => 'configurable',
                    'attribute_set' => 'Default',
                    'url_key' => 'konfigurierbarer-hoodie',
                    'url' => '/de/ausruestung/konfigurierbarer-hoodie.html',
                    'price' => 61.00,
                    'final_price' => 61.00,
                    'currency' => 'EUR',
                    'short_description' => 'Konfigurierbarer Hoodie mit Groessen- und Farbauswahl.',
                    'description' => 'Sichere Fixture-Beschreibung fuer konfigurierbare Produktdetails.',
                    'meta_title' => 'Konfigurierbarer Hoodie',
                    'meta_description' => 'Produktdetail-Fixture fuer einen konfigurierbaren Hoodie.',
                    'visibility' => 'Katalog, Suche',
                    'status' => 'Enabled',
                    'stock' => [
                        'qty' => 6,
                        'is_in_stock' => true,
                        'manage_stock' => true,
                        'backorders' => false,
                    ],
                    'rating' => [
                        'summary' => 4.7,
                        'reviews_count' => 11,
                    ],
                    'category_ids' => [2002],
                    'configurable_options' => [
                        [
                            'attribute_code' => 'size',
                            'label' => 'Groesse',
                            'values' => ['S', 'M', 'L'],
                        ],
                        [
                            'attribute_code' => 'color',
                            'label' => 'Farbe',
                            'values' => ['Schwarz', 'Grau'],
                        ],
                    ],
                    'variants' => [
                        [
                            'sku' => 'configurable-hoodie-black-m',
                            'attributes' => ['color' => 'Schwarz', 'size' => 'M'],
                            'price' => 61.00,
                            'is_in_stock' => true,
                        ],
                    ],
                    'related_skus' => ['simple-shirt'],
                    'upsell_skus' => ['simple-shirt'],
                    'cross_sell_skus' => ['downloadable-size-guide'],
                    'media_entity_ids' => [7004],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'base_image' => 'catalog/product/simple-shirt/main.jpg',
                    'small_image' => 'catalog/product/simple-shirt/small.jpg',
                    'thumbnail' => 'catalog/product/simple-shirt/thumb.jpg',
                    'missing_media' => false,
                    'gallery' => [
                        [
                            'file' => 'catalog/product/simple-shirt/main.jpg',
                            'label' => 'Simple Shirt front',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                        [
                            'file' => 'catalog/product/simple-shirt/detail.jpg',
                            'label' => 'Simple Shirt detail',
                            'position' => 2,
                            'disabled' => false,
                            'types' => [],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'base_image' => 'catalog/product/configurable-hoodie/main.jpg',
                    'small_image' => 'catalog/product/configurable-hoodie/small.jpg',
                    'thumbnail' => 'catalog/product/configurable-hoodie/thumb.jpg',
                    'missing_media' => true,
                    'missing_files' => ['catalog/product/configurable-hoodie/missing-swatch.jpg'],
                    'gallery' => [
                        [
                            'file' => 'catalog/product/configurable-hoodie/main.jpg',
                            'label' => 'Configurable Hoodie front',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7003,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'simple-shirt',
                    'base_image' => 'catalog/product/simple-shirt/main.jpg',
                    'small_image' => 'catalog/product/simple-shirt/small.jpg',
                    'thumbnail' => 'catalog/product/simple-shirt/thumb.jpg',
                    'missing_media' => false,
                    'gallery' => [
                        [
                            'file' => 'catalog/product/simple-shirt/main.jpg',
                            'label' => 'Einfaches Hemd Vorderseite',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'product_media',
                'entity_id' => 7004,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'configurable-hoodie',
                    'base_image' => 'catalog/product/configurable-hoodie/main.jpg',
                    'small_image' => 'catalog/product/configurable-hoodie/small.jpg',
                    'thumbnail' => 'catalog/product/configurable-hoodie/thumb.jpg',
                    'missing_media' => true,
                    'missing_files' => ['catalog/product/configurable-hoodie/missing-swatch.jpg'],
                    'gallery' => [
                        [
                            'file' => 'catalog/product/configurable-hoodie/main.jpg',
                            'label' => 'Konfigurierbarer Hoodie Vorderseite',
                            'position' => 1,
                            'disabled' => false,
                            'types' => ['image', 'small_image', 'thumbnail'],
                        ],
                    ],
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'shirt',
                    'filters' => [],
                    'results_count' => 1,
                    'result_skus' => ['simple-shirt'],
                    'redirect' => null,
                    'synonyms' => ['top', 'tee'],
                    'canonical_url' => '/catalogsearch/result/?q=shirt',
                    'rss_url' => '/rss/catalog/notifystock/?q=shirt',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4002,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'query_type' => 'advanced',
                    'query' => 'hoodie under 60',
                    'filters' => [
                        'category' => 'Gear',
                        'price' => ['from' => 0, 'to' => 60],
                        'visibility' => 'Catalog, Search',
                    ],
                    'results_count' => 1,
                    'result_skus' => ['configurable-hoodie'],
                    'redirect' => null,
                    'synonyms' => ['sweatshirt', 'pullover'],
                    'canonical_url' => '/catalogsearch/advanced/result/?category=gear&price[to]=60&q=hoodie',
                    'rss_url' => '/rss/catalog/special/?q=hoodie',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4003,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'legacy jacket',
                    'filters' => [],
                    'results_count' => 0,
                    'result_skus' => [],
                    'redirect' => [
                        'target' => '/gear/configurable-hoodie.html',
                        'type' => 302,
                        'reason' => 'search synonym redirect',
                    ],
                    'synonyms' => ['hoodie', 'sweatshirt'],
                    'canonical_url' => '/catalogsearch/result/?q=legacy+jacket',
                    'rss_url' => '/rss/catalog/notifystock/?q=legacy+jacket',
                    'is_index_stale' => true,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4004,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'hemd',
                    'filters' => [],
                    'results_count' => 1,
                    'result_skus' => ['simple-shirt'],
                    'redirect' => null,
                    'synonyms' => ['shirt', 'oberteil'],
                    'canonical_url' => '/de/catalogsearch/result/?q=hemd',
                    'rss_url' => '/de/rss/catalog/notifystock/?q=hemd',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4005,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'query_type' => 'advanced',
                    'query' => 'hoodie bis 65',
                    'filters' => [
                        'category' => 'Ausrustung',
                        'price' => ['from' => 0, 'to' => 65],
                        'visibility' => 'Katalog, Suche',
                    ],
                    'results_count' => 1,
                    'result_skus' => ['configurable-hoodie'],
                    'redirect' => null,
                    'synonyms' => ['kapuzenpullover', 'pullover'],
                    'canonical_url' => '/de/catalogsearch/advanced/result/?category=ausrustung&price[to]=65&q=hoodie',
                    'rss_url' => '/de/rss/catalog/special/?q=hoodie',
                    'is_index_stale' => false,
                ]),
            ],
            [
                'feature_key' => 'search',
                'entity_id' => 4006,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'query_type' => 'quick',
                    'query' => 'winterjacke',
                    'filters' => [],
                    'results_count' => 0,
                    'result_skus' => [],
                    'redirect' => [
                        'target' => '/de/ausrustung/konfigurierbarer-hoodie.html',
                        'type' => 302,
                        'reason' => 'search synonym redirect',
                    ],
                    'synonyms' => ['hoodie', 'kapuzenpullover'],
                    'canonical_url' => '/de/catalogsearch/result/?q=winterjacke',
                    'rss_url' => '/de/rss/catalog/notifystock/?q=winterjacke',
                    'is_index_stale' => true,
                ]),
            ],
            [
                'feature_key' => 'customer',
                'entity_id' => 5001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'customer_id' => 5001,
                    'email' => 'maria.sommer@example.test',
                    'firstname' => 'Maria',
                    'lastname' => 'Sommer',
                    'full_name' => 'Maria Sommer',
                    'group' => 'General',
                    'is_active' => true,
                    'created_at' => '2026-01-15T10:30:00+00:00',
                    'last_login_at' => '2026-05-10T08:15:00+00:00',
                    'orders_count' => 3,
                    'lifetime_value' => 184.70,
                    'newsletter_subscribed' => true,
                    'default_billing_address_id' => 6001,
                    'default_shipping_address_id' => 6001,
                ]),
            ],
            [
                'feature_key' => 'customer',
                'entity_id' => 5002,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'customer_id' => 5002,
                    'email' => 'lena.keller@example.test',
                    'firstname' => 'Lena',
                    'lastname' => 'Keller',
                    'full_name' => 'Lena Keller',
                    'group' => 'Retail Kunde',
                    'is_active' => true,
                    'created_at' => '2026-02-20T11:45:00+00:00',
                    'last_login_at' => '2026-05-12T07:20:00+00:00',
                    'orders_count' => 2,
                    'lifetime_value' => 129.90,
                    'newsletter_subscribed' => false,
                    'default_billing_address_id' => 6002,
                    'default_shipping_address_id' => 6002,
                ]),
            ],
            [
                'feature_key' => 'customer_address',
                'entity_id' => 6001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'address_id' => 6001,
                    'customer_id' => 5001,
                    'address_type' => 'billing_shipping',
                    'firstname' => 'Maria',
                    'lastname' => 'Sommer',
                    'company' => 'Example Retail LLC',
                    'street' => ['101 Market Street', 'Suite 400'],
                    'city' => 'Portland',
                    'region' => 'Oregon',
                    'postcode' => '97204',
                    'country_id' => 'US',
                    'telephone' => '+1-503-555-0198',
                    'is_default_billing' => true,
                    'is_default_shipping' => true,
                    'formatted_lines' => [
                        'Maria Sommer',
                        'Example Retail LLC',
                        '101 Market Street, Suite 400',
                        'Portland, Oregon 97204',
                        'US',
                    ],
                ]),
            ],
            [
                'feature_key' => 'customer_address',
                'entity_id' => 6002,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'address_id' => 6002,
                    'customer_id' => 5002,
                    'address_type' => 'billing_shipping',
                    'firstname' => 'Lena',
                    'lastname' => 'Keller',
                    'company' => 'Beispiel Handel GmbH',
                    'street' => ['Friedrichstrasse 40'],
                    'city' => 'Berlin',
                    'region' => 'Berlin',
                    'postcode' => '10117',
                    'country_id' => 'DE',
                    'telephone' => '+49-30-5550198',
                    'is_default_billing' => true,
                    'is_default_shipping' => true,
                    'formatted_lines' => [
                        'Lena Keller',
                        'Beispiel Handel GmbH',
                        'Friedrichstrasse 40',
                        '10117 Berlin',
                        'DE',
                    ],
                ]),
            ],
            [
                'feature_key' => 'downloadable',
                'entity_id' => 8001,
                'store_id' => 9001,
                'store_view' => 'default',
                'payload' => json_encode([
                    'sku' => 'downloadable-size-guide',
                    'title' => 'Size Guide PDF',
                    'file' => 'downloadable/files/size-guide.pdf',
                    'sample_file' => 'downloadable/samples/size-guide-sample.pdf',
                    'is_shareable' => false,
                    'requires_login' => true,
                    'permission' => 'customer_account_purchase',
                    'customer_group_permissions' => ['General'],
                    'max_downloads' => 5,
                    'related_product_skus' => ['simple-shirt', 'configurable-hoodie'],
                ]),
            ],
            [
                'feature_key' => 'downloadable',
                'entity_id' => 8002,
                'store_id' => 9002,
                'store_view' => 'de',
                'payload' => json_encode([
                    'sku' => 'downloadable-size-guide',
                    'title' => 'Groessentabelle PDF',
                    'file' => 'downloadable/files/size-guide.pdf',
                    'sample_file' => 'downloadable/samples/size-guide-sample.pdf',
                    'is_shareable' => false,
                    'requires_login' => true,
                    'permission' => 'customer_account_purchase',
                    'customer_group_permissions' => ['Retail Kunde'],
                    'max_downloads' => 5,
                    'related_product_skus' => ['simple-shirt', 'configurable-hoodie'],
                ]),
            ],
        ]);
    }
}
